### ISSUE TITLE
Cache projects for at least 24 hours

### ISSUE THREAD

**Issue by tomelm** [Yelp/yelp.github.io#4]
Repos don't change that often, we should look into caching things for a little while.

**Comment by jrfnl** [comment]
Or maybe even better: use the available GH API to retrieve the projects when building the site and only use js to retrieve the latest projects.

The website currently (at the time of writing) doesn't show any projects... and console shows the following two errors:
`"NetworkError: 403 Forbidden - https://api.github.com/users/yelp/repos?per_page=100&page=1"
repos?...&page=1
"NetworkError: 403 Forbidden - https://api.github.com/orgs/yelp/members"`
